name: Perbarui Guestbook

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 */1 * * *"

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: joshmgross/guestbook@main
      with:
        issue: 1
        approvers: |
          nattadasu
        guestbook-path: README.id.md
    - name: Perbarui Guestbook
      run: |
        if [[ `git status --porcelain` ]]; then
          git config --local user.email "actions@github.com"
          git config --local user.name "${{ github.actor }}"
          git add README.id.md
          git commit -m "✏ Update guestbook"
          git push
        fi
